### ISSUE TITLE
Add Logo to Project

### ISSUE THREAD

**Issue by vevi** [camaraproject/camara-landscape#7]
Hi
I'm part of Red Hat and we are currently listed as participants but our Logo is not display, can you please help me understand the process on how we can add our logo to the camara project?
Thanks!
![Logo-Red_Hat-B-Standard-Pantone](https://github.com/camaraproject/camara-landscape/assets/5476217/b68fd513-fd84-4a66-bf6e-23c56587d143)

**Comment by vevi** [comment]
participant in list ? https://github.com/camaraproject/Governance/blob/main/PARTICIPANTS.MD

**Comment by wrathwolf** [comment]
Hello @vevi 
In order to be able to display your logo on our website as a Participating Organization, we update the https://github.com/camaraproject/camara-landscape/blob/main/landscape.yml.
Logos must be in .svg format to be added to the Landscape and uploaded to https://github.com/camaraproject/camara-landscape/tree/main/hosted_logos

**Comment by hdamker** [comment]
@vevi You might want to reuse https://github.com/cncf/landscape/blob/master/hosted_logos/red-hat-member.svg here (except you would prefer to use a vertical version here)

**Comment by vevi** [comment]
@hdamker @wrathwolf  Let me try and thanks so much for the help. That logo is perfect! Looking forward to meet you all in the next Camara event in MWC.

**Comment by vevi** [comment]
I've just submitted a PR #10 .

Thanks for your help!!
